### PR TITLE
Allow to pass the OCaml compiler version to the bench script.

### PR DESCRIPTION
**Pull request by ppedrot**
I did not test this variant of the script though, I don't know how to connect to pendulum through ssh.

### CODE REVIEW

**Comment by ppedrot** [comment]
@gares Ping.

**Comment by gares** [comment]
Send Maxime your ssh key, do a clone in your home, have Jenkins job point there, test

**Comment by ppedrot** [comment]
@gares The script seems to be working.

**Comment by ejgallego** [comment]
So this is good to merge and deploy?

**Comment by ppedrot** [comment]
@ejgallego You need to adapt the script on pendulum to pass the right arguments, but the PR in itself is OK. An adapted script can be found in https://ci.inria.fr/coq/view/benchmarking/job/benchmark-part-of-the-branch-PR38/configure.

**Comment by ejgallego** [comment]
Can we maybe add a bit of documentation to this repo and add some maintenance info?

**Comment by ejgallego** [comment]
I can take care of this, but I'd need a ssh login I guess; @maximedenes

**Comment by ejgallego** [comment]
@ppedrot what's the reason behind the closing?

**Comment by ppedrot** [comment]
I think I'll mess with this directly, and furthermore I had to adapt the PR to current master.

**Pull request closed without merging**
