### PR TITLE
[travis] Restrict branches build to `master`.

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by ejgallego** [comment]
This doesn't work.

**Comment by SkySkimmer** [comment]
What for?

**Comment by ejgallego** [comment]
> What for?

Double status on CI check.

**Comment by SkySkimmer** [comment]
>Double status on CI check.

Is that a problem?

**Comment by ejgallego** [comment]
> Is that a problem?

Yup, it builds twice.

**Comment by SkySkimmer** [comment]
How/Why is it building twice?

**Comment by ejgallego** [comment]
Some stuff about travis.org -> travis.com migration, I forgot the right magic to fix it.

**Comment by ejgallego** [comment]
I think deleting the webhook should solve this.

**Pull request closed without merging**
