### PR TITLE
Allow to tweak the OPAM repository also for the OLD branch.

### PR DESCRIPTION
**Pull request by ppedrot**
This needs to be reflected in the script variables declared on Jenkins, but I'll do so as soon as this is merged.

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
Yup this was a strange asymmetry that we inherited.

Will merge ASAP the CI succeeds.

¿Maybe you need to adapt it BTW?

**Comment by ppedrot** [comment]
The CI should pass now.

**Comment by ppedrot** [comment]
Gaaah, the CI is broken due to the unrelated introduction of the ambiguous OCaml switch... Screw it, I'll fix this in this PR as well.

**Comment by ejgallego** [comment]
We may need to clean the caches.

**Comment by ejgallego** [comment]
@ppedrot merge when you want, I may be offline.

**Pull request merged**
